import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/sheard/NavBar";
import Footer from "./components/sheard/Footer";
import AOSProvider from "./components/Pages/AOSProvider";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Idea Vault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${inter.className} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <AOSProvider>
          <main>
            <NavBar />
            {children}
            <Footer />
          </main>
        </AOSProvider>
      </body>
    </html>
  );
}
